# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82a471009aa22c22610f9f6914ffcb56ad25fefa04daca5c1d67896e6d35670690aab7c39fd25f8c499f21fba95ace53fd5989fe01ce969db8dd473fc1b9463a

test:
  secret_key_base: fa9b6e9293ce201a2b7f6e4d9ed344bd5922f59506459b65dcce9bfde6afd3adcaac0adbb7dea963085fbbdd80a5a63092f8e19f48db912a4aaafc0779c87c44

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
